// Action Types.
export const SET_SESSION = "SET_SESSION"
export const SET_CURRENT_CATEGORY_INDEX = "SET_CURRENT_CATEGORY_INDEX"
export const SET_CATEGORY_CONFIGURATION_LIST = "SET_CATEGORY_CONFIGURATION_LIST"
export const SET_CURRENT_QUESTION_ID = "SET_CURRENT_QUESTION_ID"
export const SET_CURRENT_SCORE = "SET_CURRENT_SCORE"

// Possible houses.
export const GRYFFINDOR = "GRYFFINDOR"
export const RAVENCLAW = "RAVENCLAW"
export const HUFFLEPUFF = "HUFFLEPUFF"
export const SLYTHERIN = "SLYTHERIN"

// General Purpose Constants.
export const MAX_USERNAME_LENGTH = 15
