export const SET_SESSION = "SET_SESSION"
export const SET_CURRENT_CATEGORY_INDEX = "SET_CURRENT_CATEGORY_INDEX"
export const SET_CURRENT_CATEGORY_LIST = "SET_CURRENT_CATEGORY_LIST"
export const SET_CURRENT_QUESTION_ID = "SET_CURRENT_QUESTION_ID"
